---
openapi: 3.0.0
info:
  description: "This is an api for getting a message that will tell the receiver information on when the next trash pickup is."
  version: "1.0.0"
  title: "Grouch Trash Message Service"
  contact:
    email: "matthew.js.porter@gmail.com"
#host: "localhost:3000"
servers:
  - url: https://q6n0afvfcf.execute-api.us-east-1.amazonaws.com/Prod
  - url: //localhost:3000
#schemes:
#  - "http"
paths:
  /v1/message:
    get:
      tags:
        - "message"
      summary: "Get a message from grouch trash service about when trash pickup is"
      description: ""
      operationId: "getMessage"

      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
      security:
        - authorizer: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMessageFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  securitySchemes:
    authorizer:
      type: apiKey
      name: 'X-API-KEY'
      in: header

      x-amazon-apigateway-authtype: token
      x-amazon-apigateway-authorizer:
        type: token
        authorizerUri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthFunction.Arn}/invocations
        authorizerCredentials:
          Fn::Sub: ${AuthRole.Arn}
  schemas:
    Message:
      type: "object"
      required:
        - "text"
      properties:
        text:
          type: "string"
