---
swagger: "2.0"
info:
  description: "This is an api for getting a message that will tell the receiver information on when the next trash pickup is."
  version: "1.0.0"
  title: "Grouch Trash Message Service"
  contact:
    email: "matthew.js.porter@gmail.com"
host: "localhost:3000"
schemes:
  - "http"
paths:
  /v1/message:
    get:
      tags:
        - "message"
      summary: "Get a message from grouch trash service about when trash pickup is"
      description: ""
      operationId: "getMessage"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Message"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:545853618712:function:grouch-api-gateway-GetMessageFunction-QU8OQWPQEQ29/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
definitions:
  Message:
    type: "object"
    required:
      - "text"
    properties:
      text:
        type: "string"